# Generated by Django 5.2.3 on 2025-06-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownder_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
