# Generated by Django 5.2.3 on 2025-06-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_boards_ownder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='ownder_id',
        ),
    ]
