# Generated by Django 5.2.3 on 2025-06-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_remove_boards_ownder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
