# Generated by Django 5.2.3 on 2025-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_boards_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='ownder_id',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
