# Generated by Django 5.2.3 on 2025-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_boards_ownder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='member_count',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='task_high_priority_count',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='task_to_do_count',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='ticket_count',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
