# Generated by Django 5.2.3 on 2025-06-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0008_alter_boards_ownder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='ownder_id',
            new_name='owner_id',
        ),
    ]
