# Generated by Django 5.2.3 on 2025-06-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0009_rename_ownder_id_boards_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='owner_id',
        ),
    ]
