# Generated by Django 5.2.3 on 2025-06-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0018_rename_owner_id_boards_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='owner',
        ),
    ]
