# Generated by Django 5.2.3 on 2025-06-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0019_remove_boards_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='owner',
            field=models.IntegerField(default=True),
        ),
    ]
