# Generated by Django 5.2.3 on 2025-06-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0020_boards_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
