# Generated by Django 5.2.3 on 2025-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0021_rename_owner_boards_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='owner_id',
            field=models.IntegerField(editable=False),
        ),
    ]
