# Generated by Django 5.2.3 on 2025-06-24 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0022_alter_boards_owner_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='member_count',
        ),
        migrations.AddField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='task_high_priority_count',
            field=models.PositiveIntegerField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='boards',
            name='task_to_do_count',
            field=models.PositiveIntegerField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='boards',
            name='ticket_count',
            field=models.PositiveIntegerField(default=True, editable=False),
        ),
    ]
