# Generated by Django 5.2.3 on 2025-06-24 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0024_alter_boards_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(default=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
