# Generated by Django 5.2.3 on 2025-06-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0027_alter_boards_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='task_high_priority_count',
            new_name='tasks_high_prio_count',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='task_to_do_count',
            new_name='tasks_to_do_count',
        ),
    ]
