# Generated by Django 5.2.3 on 2025-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0030_alter_boards_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboards',
            name='user',
            field=models.IntegerField(editable=False),
        ),
    ]
