# Generated by Django 5.2.3 on 2025-06-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0031_alter_userboards_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBoards',
        ),
    ]
